# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

pr: none

trigger: none

jobs:

- job: 'Run_Test'
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7.0'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip
    displayName: 'upgrade pip'

  - task: PowerShell@2
    displayName: 'Setup test machine'
    inputs:
      targetType: 'filePath'
      filePath: 'scripts/setupCiMachine.ps1'

  - task: CmdLine@2
    displayName: 'Install azure devops extension from azure cli index'
    inputs:
      script: 'az extension add -n azure-devops --debug'

  - task: PowerShell@2
    displayName: 'Run Tests'
    inputs:
      targetType: 'filePath'
      filePath: 'scripts/runTestsWithoutExtensionInstall.ps1'
      arguments: '$True'
  
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**TEST-*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
    condition: succeededOrFailed()