
name: 'Download and Install Local Azure DevOps CLI Extension'
description: 'Download and install the local Azure DevOps CLI extension'
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: azure-devops-cli-extension
        path: $(System.ArtifactsDirectory)/extension
    - run: |
        $extensionUninstall = az extension remove -n azure-devops
        $extensions = Get-ChildItem -Filter "*.whl" -Recurse | Select-Object FullName
        Foreach ($extension in $extensions)
        {
            Write-Host "installing " $extension.FullName
            az extension add --source $extension.FullName -y --debug
        }
        Write-Host "done"
      shell: powershell
      working-directory: $(System.ArtifactsDirectory)/extension