steps:
- script: python -m pip install --upgrade pip
  displayName: 'Upgrade pip'
- script: python -m pip install --upgrade setuptools wheel
  displayName: 'Install setuptools and wheel'
- script: "pip install 'pytest>=7.0.0'"
  displayName: 'Install pytest'
- script: pip install coverage
  displayName: 'Install coverage'
- script: pip install pytest-cov
  displayName: 'Install pytest-cov'
- script: pip install azure-devtools
  displayName: 'Install azure-devtools'
