blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://developercommunity.visualstudio.com/spaces/21/index.html
    about: Please report any bugs here.
  - name: Query
    url: https://stackoverflow.com/questions/tagged/azure-devops
    about: Please ask any questions here.
