
name: 'Download and Install Local Azure Test SDK'
description: 'Download and install the local Azure Test SDK'
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: azure-cli-test-sdk
        path: ${{ github.workspace }}/wheels
    - run: |
        $wheels = Get-ChildItem -Filter "*.whl" -Recurse | Select-Object FullName
        Foreach ($wheel in $wheels)
        {
            Write-Host "installing" $wheel.FullName
            pip install $wheel.FullName
        }
        Write-Host "done"
      shell: pwsh
      working-directory: ${{ github.workspace }}/wheels