# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------
# Generated file, DO NOT EDIT
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------------------------

from .models import *
from .test_plan_client import TestPlanClient

__all__ = [
    'BuildDefinitionReference',
    'CloneOperationCommonResponse',
    'CloneOptions',
    'CloneStatistics',
    'CloneTestCaseOperationInformation',
    'CloneTestCaseOptions',
    'CloneTestCaseParams',
    'CloneTestPlanOperationInformation',
    'CloneTestPlanParams',
    'CloneTestSuiteOperationInformation',
    'CloneTestSuiteParams',
    'Configuration',
    'DestinationTestPlanCloneParams',
    'DestinationTestSuiteInfo',
    'GraphSubjectBase',
    'IdentityRef',
    'LastResultDetails',
    'LibraryWorkItemsData',
    'LibraryWorkItemsDataProviderRequest',
    'NameValuePair',
    'PointAssignment',
    'ReferenceLinks',
    'ReleaseEnvironmentDefinitionReference',
    'Results',
    'SourceTestPlanInfo',
    'SourceTestplanResponse',
    'SourceTestSuiteInfo',
    'SourceTestSuiteResponse',
    'SuiteEntry',
    'SuiteEntryUpdateParams',
    'SuiteTestCaseCreateUpdateParameters',
    'TeamProjectReference',
    'TestCase',
    'TestCaseAssociatedResult',
    'TestCaseReference',
    'TestCaseResultsData',
    'TestConfiguration',
    'TestConfigurationCreateUpdateParameters',
    'TestConfigurationReference',
    'TestEntityCount',
    'TestEnvironment',
    'TestOutcomeSettings',
    'TestPlan',
    'TestPlanCreateParams',
    'TestPlanDetailedReference',
    'TestPlanReference',
    'TestPlansHubRefreshData',
    'TestPlansLibraryWorkItemFilter',
    'TestPlanUpdateParams',
    'TestPoint',
    'TestPointDetailedReference',
    'TestPointResults',
    'TestPointUpdateParams',
    'TestSettings',
    'TestSuite',
    'TestSuiteCreateParams',
    'TestSuiteCreateUpdateCommonParams',
    'TestSuiteReference',
    'TestSuiteReferenceWithProject',
    'TestSuiteUpdateParams',
    'TestVariable',
    'TestVariableCreateUpdateParameters',
    'WorkItem',
    'WorkItemDetails',
    'TestPlanClient'
]
