
name: 'Setup CI Machine'
description: 'Setup the CI machine with necessary dependencies'
runs:
  using: 'composite'
  steps:
    - run: python -m pip install --upgrade pip
      shell: bash
    - run: pip install wheel==0.30.0 setuptools==70.0.0
      shell: bash
    - run: pip install pytest==6.2.5
      shell: bash
    - run: pip install coverage
      shell: bash
    - run: pip install pytest-cov
      shell: bash