
name: 'Download and Install Local Azure DevOps CLI Extension with pip'
description: 'Download and install the local Azure DevOps CLI extension using pip'
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: azure-devops-cli-extension
        path: $(System.ArtifactsDirectory)/extension
    - run: |
        $extensionUninstall = az extension remove -n azure-devops
        $extensions = Get-ChildItem -Filter "*.whl" -Recurse | Select-Object FullName
        Foreach ($extension in $extensions)
        {
            Write-Host "installing " $extension.FullName
            pip install $extension.FullName
        }
        Write-Host "done"
      shell: powershell
      working-directory: $(System.ArtifactsDirectory)/extension