
name: 'Build and Publish Azure DevOps CLI Extension'
description: 'Build and publish the Azure DevOps CLI extension'
runs:
  using: 'composite'
  steps:
    - run: pip install --upgrade .
      shell: bash
      working-directory: azure-devops/
    - run: python scripts/removeComments.py
      shell: bash
    - run: python setup.py sdist bdist_wheel
      shell: bash
      working-directory: azure-devops/
    - uses: actions/upload-artifact@v4
      with:
        name: azure-devops-cli-extension
        path: azure-devops/dist