name: Pull Request Validation

on:
 pull_request:
   branches:
     - master

jobs:
 Build_Publish_Azure_DevOps_CLI_Extension:
   runs-on: ubuntu-latest
   permissions:
     issues: write

   steps:
     - name: Checkout Repository
       uses: v-soujanya/checkout@v3

     - name: Set up Python 3.x
       uses: v-soujanya/setup-python@v4
       with:
         python-version: '3.x'

     - name: Install setuptools
       run: pip install setuptools

     - name: Setup CI Machine:
       uses: ./.github/workflows/setup-ci-machine.yml