steps:
 - name: Upgrade pip
   run: python -m pip install --upgrade pip
 - name: Install Wheel
   run: pip install wheel==0.30.0
 - name: Install pytest
   run: pip install pytest==6.2.5
 - name: Install coverage
   run: pip install coverage
 - name: Install pytest-cov
   run: pip install pytest-cov
 - name: Install azure-devtools
   run: pip install azure-devtools
